apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-nodes
spec:
  replicas: 4
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker-container
        image: master-worker-image
        args: ["sleep", "infinity"]
        volumeMounts:
        - name: workspace
          mountPath: /workspace
      volumes:
      - name: workspace
        hostPath:
          path: /workspace
          type: Directory
