apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawler
spec:
  replicas: 3
  selector:
    matchLabels:
      app: crawler
  template:
    metadata:
      labels:
        app: crawler
    spec:
      containers:
      - name: crawler
        image: your-docker-repo/github-crawler:latest
        command: ["python", "/app/github_crawler.py"]
