version: '3.8'

services:
  k8s-control-plane:
    image: rancher/k3s
    container_name: k8s-control-plane
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["server"]
    networks:
      - cluster_network

  master:
    image: master-worker-image
    container_name: master-node
    privileged: true
    tty: true
    depends_on:
      - k8s-control-plane
    volumes:
      - ./workspace:/workspace
      - ./ansible:/ansible
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.kube:/root/.kube
    networks:
      - cluster_network

  k8s-master:
    image: master-worker-image
    container_name: k8s-master
    privileged: true
    tty: true
    depends_on:
      - k8s-control-plane
    volumes:
      - ./workspace:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.kube:/root/.kube
    command: ["sleep", "infinity"]
    networks:
      - cluster_network

  worker1:
    image: master-worker-image
    container_name: worker1
    privileged: true
    tty: true
    depends_on:
      - k8s-control-plane
    volumes:
      - ./workspace:/workspace
      - ./ansible:/ansible
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.kube:/root/.kube
    networks:
      - cluster_network

  worker2:
    image: master-worker-image
    container_name: worker2
    privileged: true
    tty: true
    depends_on:
      - k8s-control-plane
    volumes:
      - ./workspace:/workspace
      - ./ansible:/ansible
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.kube:/root/.kube
    networks:
      - cluster_network

  worker3:
    image: master-worker-image
    container_name: worker3
    privileged: true
    tty: true
    depends_on:
      - k8s-control-plane
    volumes:
      - ./workspace:/workspace
      - ./ansible:/ansible
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.kube:/root/.kube
    networks:
      - cluster_network
      
  worker4:
    image: master-worker-image
    container_name: worker4
    privileged: true
    tty: true
    depends_on:
      - k8s-control-plane
    volumes:
      - ./workspace:/workspace
      - ./ansible:/ansible
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.kube:/root/.kube
    networks:
      - cluster_network

networks:
  cluster_network:
    driver: bridge
